### PR TITLE
More accuracy about the current state of the project.

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Ezibenroc** [comment]
I agree this has to be reformulated. But I find your sentence a bit pessimist, as if it was a miracle that this project is still alive...

I don't know how to put more enthusiasm...

**Comment by ProgVal** [comment]
s/but/and/ ?

**Comment by Ezibenroc** [comment]
Yes it would be better. The "still alive" is also anoying, as if the project unexpectedly survived.

**Comment by Ezibenroc** [comment]
I prefer what @Tpt wrote here: https://github.com/ProjetPP/projetpp.github.io/commit/6b9d846b5347d511a07bb083e3b4a5c81302bd32

>"This project has begun as a student project at the [École Normale Supérieure de Lyon](http://www.ens-lyon.fr/DI/?lang=en)".

I suggest to delete this branch and keep the branch `rewrite`, if you agree.

**Comment by Tpt** [comment]
Strong +1. Saying that the project is "still alive" may means that it's dying slowly, and it's not what we want to say.

**Pull request closed without merging**
