### PR TITLE
Reformulation

### PR DESCRIPTION
**Pull request by yhamoudi**

### CODE REVIEW

**Comment by Ezibenroc** [comment]
What do you think of "This project has begun as the student project of seven students in first year of the theoretical computer science master of the [École Normale Supérieure de Lyon](http://www.ens-lyon.fr/DI/?lang=en):"?

I agree that the "was done" give the impression that the project is no longer active. But I find the "run" inappropriate.

**Comment by yhamoudi** [comment]
In fact there are too many repeats in your sentence (and mine) : project x2, student x2. Perhaps it's less shocking when the sentence is split in 2 parts (but another formulation would be better).

(the "run" means ["mené par"](http://www.linguee.fr/francais-anglais/search?source=auto&query=il+est+men%E9+par), i don't thinks it's strange in english)

**Comment by yhamoudi** [comment]
What about:
> This project has begun at the [École Normale Supérieure de Lyon](http://www.ens-lyon.fr/DI/?lang=en). It is run by seven students in theoretical computer science.

**Comment by Ezibenroc** [comment]
It is better. But what if we have new contributors?

**Comment by yhamoudi** [comment]
we add a new line below to thanks the main contributors

**Comment by Ezibenroc** [comment]
Ok. I let you change the sentence.

**Pull request merged**
